spring:
  datasource:
#    url: jdbc:postgresql://ls-9677815d660984cb4cc4f7ca8605c63654afa074.c2pl7qcogrbm.ap-southeast-1.rds.amazonaws.com:5432/postgres
#    username: dbmasteruser
#    password: +6_Vw~YT4lz&zVZ&O,C81&jY4{J.BqCW
    url: jdbc:postgresql://18.138.255.183:5432/postgres
    username: postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        format_sql: true
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

  database-platform: org.hibernate.dialect.PostgreSQLDialect

