spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vcr_db
    username: postgres
    password: 1234
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

